### ISSUE TITLE
How do you add Google Calendar?

### ISSUE THREAD

**Issue by Gatienzo** [poulicek/WLCalendarGadget#1]
Hi. I am sorry to ask here but I do not see how to add Google Calendar. I checked options but can´t see how. Thanks.

**Comment by Gatienzo** [comment]
Now I know how to obtain the URL to share a Google calendar. I pasted it in the window in options but an error message reads that it can´t be loaded.

**Comment by poulicek** [comment]
Sorry,  I missed this post... It works for me. Could you please check that you've used the URL from "Secret address in iCal format"? (To be found in the Google Calendar settings)

![image](https://user-images.githubusercontent.com/49347649/184176221-9aa10857-742d-491e-ae39-12fc512087de.png)

**Comment by Gatienzo** [comment]
Thanks, it worked.
Where do you put the weather URL? In the same window as the calendar URL? That does not work for me.
