### ISSUE TITLE
Could not load calendar error

### ISSUE THREAD

**Issue by MechanicalWhispers** [poulicek/WLCalendarGadget#2]
For a few weeks now, whenever I turn on my computer and this Gadget loads, it gives the error that it cannot load the calendar. Then, if I open and close settings, it loads the calendar. Anyone know why?

**Comment by poulicek** [comment]
The gadaget caches the lastest synced data so even if the Internet is not available during its startup, it should be able to display the previous state. It may be that the cache is somehow corrupted. I'd recommend to remove and add again the current setting (or maybe even reinstall the gadget). I've done a test on Windows 11 with linked Google calendar and wasn't able to reproduce the issue.

**Comment by MechanicalWhispers** [comment]
Thank you for your reply. I tried uninstalling it (and the Gadget Support sidebar). I also copied new private links to my Google calendars in iCal format. Things seem to be working now, and I have not seen the error. I'm wondering if it was just that my iCal links expired or changed or something? Anyway, thank you for your help, and for making a great Gadget!
